In [1]:
import numpy as np
data = np.loadtxt("haberman1.txt")
X = data[:,0:3]
y = data[:,3]
print X
print y
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.2,random_state=42)
from sklearn.linear_model import LogisticRegression
model_log = LogisticRegression()
model_log = model_log.fit(X_train,y_train)
print "Train Accuracy for Logistic Regression Model",model_log.score(X_train,y_train)
print "Test Accuracy for Logistic Regression Model",model_log.score(X_test,y_test)

[[ 30.  64.   1.]
 [ 30.  62.   3.]
 [ 30.  65.   0.]
 [ 31.  59.   2.]
 [ 31.  65.   4.]
 [ 33.  58.  10.]
 [ 33.  60.   0.]
 [ 34.  59.   0.]
 [ 34.  66.   9.]
 [ 34.  58.  30.]
 [ 34.  60.   1.]
 [ 34.  61.  10.]
 [ 34.  67.   7.]
 [ 34.  60.   0.]
 [ 35.  64.  13.]
 [ 35.  63.   0.]
 [ 36.  60.   1.]
 [ 36.  69.   0.]
 [ 37.  60.   0.]
 [ 37.  63.   0.]
 [ 37.  58.   0.]
 [ 37.  59.   6.]
 [ 37.  60.  15.]
 [ 37.  63.   0.]
 [ 38.  69.  21.]
 [ 38.  59.   2.]
 [ 38.  60.   0.]
 [ 38.  60.   0.]
 [ 38.  62.   3.]
 [ 38.  64.   1.]
 [ 38.  66.   0.]
 [ 38.  66.  11.]
 [ 38.  60.   1.]
 [ 38.  67.   5.]
 [ 39.  66.   0.]
 [ 39.  63.   0.]
 [ 39.  67.   0.]
 [ 39.  58.   0.]
 [ 39.  59.   2.]
 [ 39.  63.   4.]
 [ 40.  58.   2.]
 [ 40.  58.   0.]
 [ 40.  65.   0.]
 [ 41.  60.  23.]
 [ 41.  64.   0.]
 [ 41.  67.   0.]
 [ 41.  58.   0.]
 [ 41.  59.   8.]
 [ 41.  59.   0.]
 [ 41.  64.   0.]
 [ 41.  69.   8.]
 [ 41.  65.   0.]
 [ 41.  65.   0.]
 [ 42.  69.   1.]
 [ 42.  59.   0.]
 [ 42.  58

C:\Users\Kabir\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Train Accuracy for Logistic Regression Model 0.762295081967
Test Accuracy for Logistic Regression Model 0.693548387097


In [2]:
from sklearn import svm
model_svm = svm.SVC()
model_svm = model_svm.fit(X_train,y_train)
print "Train Accuracy for SVM Model",model_svm.score(X_train,y_train)
print "Test Accuracy for SVM Model",model_svm.score(X_test,y_test)

Train Accuracy for SVM Model 0.922131147541
Test Accuracy for SVM Model 0.709677419355


In [3]:
from sklearn.tree import DecisionTreeClassifier

In [4]:
model_tree = DecisionTreeClassifier()
model_tree = model_tree.fit(X_train,y_train)
print "Train Accuracy for Decision Tree Model",model_tree.score(X_train,y_train)
print "Test Accuracy for Decison Tree Model",model_tree.score(X_test,y_test)

Train Accuracy for Decision Tree Model 0.983606557377
Test Accuracy for Decison Tree Model 0.661290322581


In [5]:
model_tree2 = DecisionTreeClassifier(max_depth=3)
model_tree2 = model_tree2.fit(X_train,y_train)
print "Train Accuracy for Decision Tree2 Model",model_tree2.score(X_train,y_train)
print "Test Accuracy for Decison Tree2 Model",model_tree2.score(X_test,y_test)

Train Accuracy for Decision Tree2 Model 0.803278688525
Test Accuracy for Decison Tree2 Model 0.709677419355


In [6]:
count = 0
for i in range(len(y_test)):
    if y_test[i] == 1:
        count+=1
maj_acc = float(count)/len(y_test)

In [7]:
print maj_acc

0.709677419355


In [8]:
print y_test
print tree2.predict(X_test)

[ 1.  1.  1.  1.  1.  1.  1.  2.  2.  1.  1.  1.  2.  1.  1.  1.  2.  1.
  1.  2.  1.  1.  1.  1.  1.  2.  1.  2.  2.  2.  1.  1.  1.  1.  1.  1.
  1.  2.  2.  1.  2.  1.  1.  1.  2.  1.  1.  1.  1.  1.  2.  1.  2.  2.
  1.  2.  1.  1.  1.  1.  2.  1.]


NameError: name 'tree2' is not defined

In [9]:
print y_test
print model_tree2.predict(X_test)

[ 1.  1.  1.  1.  1.  1.  1.  2.  2.  1.  1.  1.  2.  1.  1.  1.  2.  1.
  1.  2.  1.  1.  1.  1.  1.  2.  1.  2.  2.  2.  1.  1.  1.  1.  1.  1.
  1.  2.  2.  1.  2.  1.  1.  1.  2.  1.  1.  1.  1.  1.  2.  1.  2.  2.
  1.  2.  1.  1.  1.  1.  2.  1.]
[ 1.  1.  1.  1.  1.  2.  1.  1.  2.  1.  1.  1.  1.  2.  1.  1.  1.  1.
  2.  1.  1.  1.  1.  1.  1.  1.  1.  2.  1.  2.  1.  2.  1.  1.  1.  1.
  1.  1.  1.  1.  2.  1.  2.  1.  1.  1.  1.  1.  1.  1.  2.  1.  1.  1.
  1.  2.  2.  1.  1.  1.  1.  1.]


In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
model_forest = RandomForestClassifier(n_estimators=10, criterion='gini', max_depth=None,min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None,bootstrap=True, oob_score=False, n_jobs=1, random_state=None, verbose=0, warm_start=False,class_weight=None)

In [12]:
model_forest = model_forest.fit(X_train,y_train)
print "Train Accuracy for forest Model",model_forest.score(X_train,y_train)
print "Test Accuracy for forest Model",model_forest.score(X_test,y_test)

Train Accuracy for forest Model 0.959016393443
Test Accuracy for forest Model 0.661290322581


In [13]:
import sklearn.metrics

In [14]:
print "precision of log Model", sklearn.mertics.precision_score(y_test,model_log.predict(y_test))

precision of log Model

AttributeError: 'module' object has no attribute 'mertics'

In [15]:
print "precision of log Model", precision_score(y_test,model_log.predict(y_test))

 precision of log Model

NameError: name 'precision_score' is not defined

In [16]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [17]:
from sklearn.metrics import F_score

ImportError: cannot import name F_score

In [18]:
from sklearn.metrics import Fscore

ImportError: cannot import name Fscore

In [19]:
print "precision of log Model", precision_score(y_test,model_log.predict(y_test))

precision of log Model

C:\Users\Kabir\Anaconda2\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


ValueError: X has 62 features per sample; expecting 3

In [20]:
print "precision of log Model", precision_score(y_test,model_log.predict(X_test))

 precision of log Model 0.727272727273


In [21]:
print "recall of log Model", recall_score(y_test,model_log.predict(X_test))

recall of log Model 0.909090909091


In [22]:
from sklearn.metrics import f1_score

In [23]:
print "f1score of log Model", f1_score(y_test,model_log.predict(X_test))

f1score of log Model 0.808080808081


In [24]:
print "precision of svm Model", precision_score(y_test,model_svm.predict(X_test))
print "recall of svm Model", recall_score(y_test,model_svm.predict(X_test))
print "f1score of svm Model", f1_score(y_test,model_svm.predict(X_test))

precision of svm Model 0.709677419355
recall of svm Model 1.0
f1score of svm Model 0.830188679245


In [25]:
print "precision of tree Model", precision_score(y_test,model_tree.predict(X_test))
print "recall of tree Model", recall_score(y_test,model_tree.predict(X_test))
print "f1score of tree Model", f1_score(y_test,model_tree.predict(X_test))

precision of tree Model 0.744680851064
recall of tree Model 0.795454545455
f1score of tree Model 0.769230769231


In [26]:
print "precision of tree2 Model", precision_score(y_test,model_tree2.predict(X_test))
print "recall of tree2 Model", recall_score(y_test,model_tree2.predict(X_test))
print "f1score of tree2 Model", f1_score(y_test,model_tree2.predict(X_test))

precision of tree2 Model 0.76
recall of tree2 Model 0.863636363636
f1score of tree2 Model 0.808510638298


In [27]:
print "Best model for our data is SVM"

Best model for our data is SVM
