In [1]:
import numpy as np
#loading the data to numpy array
data = np.loadtxt("haberman1.txt")
X = data[:,0:3]
y = data[:,3]
print X
print y
from sklearn.cross_validation import train_test_split
#splitting the data into training and test data
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.2,random_state=40)
#Applying Logistic Regression on our data
from sklearn.linear_model import LogisticRegression
model_log = LogisticRegression()
model_log = model_log.fit(X_train,y_train)
print "Train Accuracy for Logistic Regression Model",model_log.score(X_train,y_train)
print "Test Accuracy for Logistic Regression Model",model_log.score(X_test,y_test)
#Applying SVM on our data
from sklearn import svm
model_svm = svm.SVC()
model_svm = model_svm.fit(X_train,y_train)
print "Train Accuracy for SVM Model",model_svm.score(X_train,y_train)
print "Test Accuracy for SVM Model",model_svm.score(X_test,y_test)
from sklearn.tree import DecisionTreeClassifier
model_tree = DecisionTreeClassifier()
model_tree = model_tree.fit(X_train,y_train)
print "Train Accuracy for Decision Tree Model",model_tree.score(X_train,y_train)
print "Test Accuracy for Decison Tree Model",model_tree.score(X_test,y_test)
model_tree2 = DecisionTreeClassifier(max_depth=3)
model_tree2 = model_tree2.fit(X_train,y_train)
print "Train Accuracy for Decision Tree2 Model",model_tree2.score(X_train,y_train)
print "Test Accuracy for Decison Tree2 Model",model_tree2.score(X_test,y_test)
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
print "precision of log Model", precision_score(y_test,model_log.predict(X_test))
print "recall of log Model", recall_score(y_test,model_log.predict(X_test))
print "f1score of log Model", f1_score(y_test,model_log.predict(X_test))
print "precision of svm Model", precision_score(y_test,model_svm.predict(X_test))
print "recall of svm Model", recall_score(y_test,model_svm.predict(X_test))
print "f1score of svm Model", f1_score(y_test,model_svm.predict(X_test))
print "precision of tree Model", precision_score(y_test,model_tree.predict(X_test))
print "recall of tree Model", recall_score(y_test,model_tree.predict(X_test))
print "f1score of tree Model", f1_score(y_test,model_tree.predict(X_test))
print "precision of tree2 Model", precision_score(y_test,model_tree2.predict(X_test))
print "recall of tree2 Model", recall_score(y_test,model_tree2.predict(X_test))
print "f1score of tree2 Model", f1_score(y_test,model_tree2.predict(X_test))
print "Best model for our data is SVM"

[[ 30.  64.   1.]
 [ 30.  62.   3.]
 [ 30.  65.   0.]
 [ 31.  59.   2.]
 [ 31.  65.   4.]
 [ 33.  58.  10.]
 [ 33.  60.   0.]
 [ 34.  59.   0.]
 [ 34.  66.   9.]
 [ 34.  58.  30.]
 [ 34.  60.   1.]
 [ 34.  61.  10.]
 [ 34.  67.   7.]
 [ 34.  60.   0.]
 [ 35.  64.  13.]
 [ 35.  63.   0.]
 [ 36.  60.   1.]
 [ 36.  69.   0.]
 [ 37.  60.   0.]
 [ 37.  63.   0.]
 [ 37.  58.   0.]
 [ 37.  59.   6.]
 [ 37.  60.  15.]
 [ 37.  63.   0.]
 [ 38.  69.  21.]
 [ 38.  59.   2.]
 [ 38.  60.   0.]
 [ 38.  60.   0.]
 [ 38.  62.   3.]
 [ 38.  64.   1.]
 [ 38.  66.   0.]
 [ 38.  66.  11.]
 [ 38.  60.   1.]
 [ 38.  67.   5.]
 [ 39.  66.   0.]
 [ 39.  63.   0.]
 [ 39.  67.   0.]
 [ 39.  58.   0.]
 [ 39.  59.   2.]
 [ 39.  63.   4.]
 [ 40.  58.   2.]
 [ 40.  58.   0.]
 [ 40.  65.   0.]
 [ 41.  60.  23.]
 [ 41.  64.   0.]
 [ 41.  67.   0.]
 [ 41.  58.   0.]
 [ 41.  59.   8.]
 [ 41.  59.   0.]
 [ 41.  64.   0.]
 [ 41.  69.   8.]
 [ 41.  65.   0.]
 [ 41.  65.   0.]
 [ 42.  69.   1.]
 [ 42.  59.   0.]
 [ 42.  58

C:\Users\Kabir\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Train Accuracy for Logistic Regression Model 0.745901639344
Test Accuracy for Logistic Regression Model 0.774193548387
Train Accuracy for SVM Model 0.901639344262
Test Accuracy for SVM Model 0.774193548387
Train Accuracy for Decision Tree Model 0.991803278689
Test Accuracy for Decison Tree Model 0.661290322581
Train Accuracy for Decision Tree2 Model 0.790983606557
Test Accuracy for Decison Tree2 Model 0.758064516129
precision of log Model 0.803571428571
recall of log Model 0.9375
f1score of log Model 0.865384615385
precision of svm Model 0.774193548387
recall of svm Model 1.0
f1score of svm Model 0.872727272727
precision of tree Model 0.864864864865
recall of tree Model 0.666666666667
f1score of tree Model 0.752941176471
precision of tree2 Model 0.823529411765
recall of tree2 Model 0.875
f1score of tree2 Model 0.848484848485
Best model for our data is SVM


In [1]:
import numpy as np
#loading the data to numpy array
data = np.loadtxt("haberman1.txt")
X = data[:,0:3]
y = data[:,3]
print X
print y
from sklearn.cross_validation import train_test_split
#splitting the data into training and test data
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.2,random_state=40)
#Applying Logistic Regression on our data
from sklearn.linear_model import LogisticRegression
model_log = LogisticRegression()
model_log = model_log.fit(X_train,y_train)
print "Train Accuracy for Logistic Regression Model",model_log.score(X_train,y_train)
print "Test Accuracy for Logistic Regression Model",model_log.score(X_test,y_test)
#Applying SVM on our data
from sklearn import svm
model_svm = svm.SVC()
model_svm = model_svm.fit(X_train,y_train)
print "Train Accuracy for SVM Model",model_svm.score(X_train,y_train)
print "Test Accuracy for SVM Model",model_svm.score(X_test,y_test)
from sklearn.tree import DecisionTreeClassifier
model_tree = DecisionTreeClassifier()
model_tree = model_tree.fit(X_train,y_train)
print "Train Accuracy for Decision Tree Model",model_tree.score(X_train,y_train)
print "Test Accuracy for Decison Tree Model",model_tree.score(X_test,y_test)
model_tree2 = DecisionTreeClassifier(max_depth=3)
model_tree2 = model_tree2.fit(X_train,y_train)
print "Train Accuracy for Decision Tree2 Model",model_tree2.score(X_train,y_train)
print "Test Accuracy for Decison Tree2 Model",model_tree2.score(X_test,y_test)
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
print "precision of log Model", precision_score(y_test,model_log.predict(X_test))
print "recall of log Model", recall_score(y_test,model_log.predict(X_test))
print "f1score of log Model", f1_score(y_test,model_log.predict(X_test))
print "precision of svm Model", precision_score(y_test,model_svm.predict(X_test))
print "recall of svm Model", recall_score(y_test,model_svm.predict(X_test))
print "f1score of svm Model", f1_score(y_test,model_svm.predict(X_test))
print "precision of tree Model", precision_score(y_test,model_tree.predict(X_test))
print "recall of tree Model", recall_score(y_test,model_tree.predict(X_test))
print "f1score of tree Model", f1_score(y_test,model_tree.predict(X_test))
print "precision of tree2 Model", precision_score(y_test,model_tree2.predict(X_test))
print "recall of tree2 Model", recall_score(y_test,model_tree2.predict(X_test))
print "f1score of tree2 Model", f1_score(y_test,model_tree2.predict(X_test))
print "Best model for our data is LogisticRegression"

[[ 30.  64.   1.]
 [ 30.  62.   3.]
 [ 30.  65.   0.]
 [ 31.  59.   2.]
 [ 31.  65.   4.]
 [ 33.  58.  10.]
 [ 33.  60.   0.]
 [ 34.  59.   0.]
 [ 34.  66.   9.]
 [ 34.  58.  30.]
 [ 34.  60.   1.]
 [ 34.  61.  10.]
 [ 34.  67.   7.]
 [ 34.  60.   0.]
 [ 35.  64.  13.]
 [ 35.  63.   0.]
 [ 36.  60.   1.]
 [ 36.  69.   0.]
 [ 37.  60.   0.]
 [ 37.  63.   0.]
 [ 37.  58.   0.]
 [ 37.  59.   6.]
 [ 37.  60.  15.]
 [ 37.  63.   0.]
 [ 38.  69.  21.]
 [ 38.  59.   2.]
 [ 38.  60.   0.]
 [ 38.  60.   0.]
 [ 38.  62.   3.]
 [ 38.  64.   1.]
 [ 38.  66.   0.]
 [ 38.  66.  11.]
 [ 38.  60.   1.]
 [ 38.  67.   5.]
 [ 39.  66.   0.]
 [ 39.  63.   0.]
 [ 39.  67.   0.]
 [ 39.  58.   0.]
 [ 39.  59.   2.]
 [ 39.  63.   4.]
 [ 40.  58.   2.]
 [ 40.  58.   0.]
 [ 40.  65.   0.]
 [ 41.  60.  23.]
 [ 41.  64.   0.]
 [ 41.  67.   0.]
 [ 41.  58.   0.]
 [ 41.  59.   8.]
 [ 41.  59.   0.]
 [ 41.  64.   0.]
 [ 41.  69.   8.]
 [ 41.  65.   0.]
 [ 41.  65.   0.]
 [ 42.  69.   1.]
 [ 42.  59.   0.]
 [ 42.  58

C:\Users\Kabir\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Train Accuracy for Logistic Regression Model 0.745901639344
Test Accuracy for Logistic Regression Model 0.774193548387
Train Accuracy for SVM Model 0.901639344262
Test Accuracy for SVM Model 0.774193548387
Train Accuracy for Decision Tree Model 0.991803278689
Test Accuracy for Decison Tree Model 0.645161290323
Train Accuracy for Decision Tree2 Model 0.790983606557
Test Accuracy for Decison Tree2 Model 0.758064516129
precision of log Model 0.803571428571
recall of log Model 0.9375
f1score of log Model 0.865384615385
precision of svm Model 0.774193548387
recall of svm Model 1.0
f1score of svm Model 0.872727272727
precision of tree Model 0.842105263158
recall of tree Model 0.666666666667
f1score of tree Model 0.744186046512
precision of tree2 Model 0.823529411765
recall of tree2 Model 0.875
f1score of tree2 Model 0.848484848485
Best model for our data is LogisticRegression


In [2]:
from sklearn.svm import SVR
clf = SVR()
clf = clf.fit(X_train,y_train)
clf.score(X_train,y_train)

0.83802888114358309

In [3]:
clf.score(X_test,y_test)

-0.029333221358034622

In [4]:
clf.predict(X_test)

array([ 1.70567125,  1.31059324,  1.10025922,  0.97443499,  1.09987017,
        1.34971424,  1.09957646,  1.5777979 ,  1.46657377,  1.352943  ,
        1.06797507,  1.5005987 ,  1.36463604,  1.45835834,  1.57629634,
        1.46997921,  1.27194298,  1.11854066,  1.34542698,  1.48928304,
        1.24221743,  1.14535872,  1.31920728,  1.17843246,  1.2412402 ,
        1.45007523,  1.35328187,  1.23843396,  1.11247338,  1.07507454,
        1.09972607,  1.02623295,  1.42749035,  1.35364152,  0.97238714,
        1.12404767,  1.33477647,  1.3529494 ,  1.12413179,  1.27305604,
        1.34356769,  1.34136329,  1.45620231,  1.23616716,  1.10112775,
        1.83284443,  1.16046556,  1.41285363,  1.26026575,  1.36290184,
        1.38293302,  1.37044527,  1.34390699,  1.4235694 ,  1.24776844,
        1.27506317,  1.19068496,  1.19080744,  1.33563173,  1.15825554,
        1.17843246,  1.41627513])

In [5]:
clf.predict(X_train)

array([ 1.09998611,  1.05310669,  1.09963678,  0.98711242,  0.93236647,
        1.09996553,  1.0999452 ,  1.35297048,  1.09983525,  1.10008903,
        1.10000458,  1.09972807,  1.10032742,  1.12035539,  1.10026419,
        1.10025922,  1.41285363,  1.09997101,  1.10000166,  1.10012589,
        1.09985517,  1.10042782,  1.09971762,  0.99175273,  0.96289751,
        1.10031262,  1.10039534,  1.09983754,  1.90024192,  1.90011928,
        1.09995182,  1.09983101,  1.10023969,  1.10020551,  1.04199952,
        1.90034502,  1.10000166,  0.92357168,  1.90013271,  1.00364616,
        1.03957248,  0.98613802,  1.8998276 ,  1.09980071,  1.10018841,
        1.10023761,  1.09991731,  1.09968491,  1.68935456,  0.97276164,
        1.10000481,  1.10037534,  1.09953592,  1.05862136,  1.09999268,
        1.90026071,  1.10009606,  1.10013511,  1.89949145,  1.09964683,
        1.28299536,  1.09998982,  1.90004749,  1.10009057,  1.10004067,
        1.47520326,  1.10039534,  1.09687716,  1.90001121,  1.10

In [6]:
model_svm.predict(X_test)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
X_test

array([[ 61.,  65.,   0.],
       [ 70.,  63.,   0.],
       [ 62.,  66.,   0.],
       [ 63.,  62.,   0.],
       [ 55.,  58.,   1.],
       [ 62.,  65.,  19.],
       [ 65.,  64.,   0.],
       [ 61.,  64.,   0.],
       [ 33.,  60.,   0.],
       [ 34.,  58.,  30.],
       [ 49.,  62.,   1.],
       [ 60.,  64.,   0.],
       [ 51.,  59.,  13.],
       [ 42.,  69.,   1.],
       [ 47.,  63.,   6.],
       [ 53.,  58.,   1.],
       [ 52.,  65.,   0.],
       [ 37.,  60.,   0.],
       [ 52.,  69.,   3.],
       [ 34.,  60.,   0.],
       [ 58.,  60.,   3.],
       [ 53.,  63.,   0.],
       [ 73.,  68.,   0.],
       [ 50.,  64.,   0.],
       [ 54.,  58.,   1.],
       [ 43.,  64.,   0.],
       [ 54.,  69.,   7.],
       [ 48.,  62.,   2.],
       [ 70.,  67.,   0.],
       [ 51.,  65.,   0.],
       [ 37.,  63.,   0.],
       [ 50.,  66.,   1.],
       [ 43.,  60.,   0.],
       [ 55.,  66.,  18.],
       [ 50.,  61.,   0.],
       [ 47.,  58.,   3.],
       [ 74.,  65.,   3.],
 

In [8]:
y_test

array([ 2.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,
        2.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  1.,  2.,  1.,  2.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  1.,
        1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  1.,  2.,  1.,  2.,
        2.,  1.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
for i in range(0,len(y_test)):
    if y[i] == 2:
        y[i] = 0;

In [10]:
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.2,random_state=40)

In [11]:
from sklearn.svm import SVR
clf = SVR()
clf = clf.fit(X_train,y_train)
clf.score(X_train,y_train)

0.84289800497400535

In [12]:
clf.score(X_test,y_test)

-0.03919377986280681

In [13]:
clf.predict(X_test)

array([ 1.68955323,  1.27757003,  1.10003376,  0.97720467,  1.0999108 ,
        1.30590261,  1.10002891,  1.55546529,  0.85315855,  1.30854006,
        1.06637687,  1.48670778,  1.32118081,  1.16950732,  1.55216665,
        1.44680337,  1.26879792,  1.10052533,  1.30687552,  0.66287587,
        1.2317765 ,  1.14551041,  1.28047773,  1.16277572,  1.23056428,
        1.39560009,  1.30910162,  1.22176889,  1.11169101,  1.06513529,
        1.09985797,  1.02424614,  0.93127391,  1.31096413,  0.95813122,
        1.11481322,  1.29371717,  1.30854699,  1.11409067,  1.24292004,
        1.3005414 ,  1.29349105,  1.42019388,  1.21907448,  1.10065733,
        1.80888559,  1.11369956,  0.81925462,  1.23182998,  1.31926601,
        1.35560473,  1.34340449,  1.30109113,  1.38491141,  1.21963933,
        1.27000674,  1.17777146,  1.17587727,  1.2921178 ,  1.18068908,
        1.16277572,  1.39542724])

In [14]:
model_log.predict(X_test)

array([ 1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  2.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])