In [11]:
import numpy as np
data = np.loadtxt("haberman1.txt")

In [12]:
X = data[:,0:3]
y = data[:,3]

In [13]:
y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,
        2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  1.,  1.,
        1.,  1.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,
        2.,  2.,  1.,  1.,  1.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  2.,  2.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  1.,  1.,  1.,  1.,  2.,
        2.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        2.,  2.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,
        2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2

In [14]:
for i in range(len(y)):
    if y[i]==2:
        y[i]=0
y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,
        1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,
        0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,
        0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,
        0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0

In [15]:
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

C:\Users\Kabir\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [16]:
from sklearn.linear_model import LogisticRegression


# In[12]:

model_reg=LogisticRegression()
model_reg=model_reg.fit(X_train,y_train)


# In[13]:

print model_reg.score(X_train,y_train)


# In[14]:

print model_reg.score(X_test,y_test)

0.762295081967
0.693548387097


In [17]:
from sklearn import svm
model_svm=svm.SVC()
model_svm=model_svm.fit(X_train,y_train)


# In[17]:

print model_svm.score(X_train,y_train)


# In[18]:

print model_svm.score(X_test,y_test)

0.922131147541
0.709677419355


In [18]:
from sklearn.naive_bayes import GaussianNB
clf1 = GaussianNB()
clf1 = clf1.fit(X_train,y_train)
print clf1.score(X_train,y_train)
print clf1.score(X_test,y_test)

0.762295081967
0.709677419355


In [19]:
clf1.predict(X_train)

array([ 1.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [20]:
y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,
        1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,
        0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,
        0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,
        0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0

In [21]:
clf1.predict(X_test)

array([ 1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,
        1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.])

In [22]:
y_test

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,
        1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,
        1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,
        1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        0.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.])

In [23]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
print clf.score(X_train,y_train)
print clf.score(X_test,y_test)

0.983606557377
0.645161290323


In [24]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth=4)
clf = clf.fit(X_train,y_train)
print clf.score(X_train,y_train)
print clf.score(X_test,y_test)

0.80737704918
0.677419354839


In [25]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth=2)
clf = clf.fit(X_train,y_train)
print clf.score(X_train,y_train)
print clf.score(X_test,y_test)

0.790983606557
0.725806451613


In [26]:
from sklearn.neural_network import MLPClassifier
clfneural = MLPClassifier()
clfneural = clfneural.fit(X_train,y_train)
print clfneural.score(X_train,y_train)
print clf.score(X_test,y_test)

0.725409836066
0.725806451613


In [27]:
from sklearn.neural_network import MLPClassifier
clfneural = MLPClassifier()
clfneural = clfneural.fit(X_train,y_train)
print clfneural.score(X_train,y_train)
print clfneural.score(X_test,y_test)

0.745901639344
0.709677419355


In [28]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier()
neigh = neigh.fit(X_train,y_train)

In [29]:
print neigh.score(X_train,y_train)
print neigh.score(X_test,y_test)

0.795081967213
0.661290322581


In [30]:
from sklearn.ensemble import AdaBoostClassifier
boo = AdaBoostClassifier()
boo = boo.fit(X_train,y_train)
print boo.score(X_train,y_train)

0.827868852459


In [31]:
boo.score(X_test,y_test)

0.69354838709677424

In [32]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier()
forest = forest.fit(X_train,y_train)
forest.score(X_train,y_train)

0.97131147540983609

In [33]:
forest.score(X_test,y_test)

0.67741935483870963

In [34]:
forest = RandomForestClassifier(max_depth=4)
forest = forest.fit(X_train,y_train)
forest.score(X_train,y_train)

0.84836065573770492

In [35]:
forest.score(X_test,y_test)

0.66129032258064513

In [36]:
forest = RandomForestClassifier(max_depth=2)
forest = forest.fit(X_train,y_train)
forest.score(X_train,y_train)

0.74180327868852458

In [37]:
forest.score(X_test,y_test)

0.70967741935483875

In [38]:
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [39]:
recall_score(y,clf.predict())

TypeError: predict() takes at least 2 arguments (1 given)

In [40]:
recall_score(y,clf.predict(X))

0.88888888888888884

In [41]:
precision_score(y,clf.predict(X))

0.82304526748971196

In [42]:
print recall_score(y,boo.predict(X))
print precision_score(y,boo.predict(X))

0.946666666667
0.812977099237
