In [1]:
import numpy as np
#loading the data to numpy array
data = np.loadtxt("haberman1.txt")
X = data[:,0:3]
y = data[:,3]
print X
print y
from sklearn.cross_validation import train_test_split
#splitting the data into training and test data
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.2,random_state=40)
#Applying Logistic Regression on our data
from sklearn.linear_model import LogisticRegression
model_log = LogisticRegression()
model_log = model_log.fit(X_train,y_train)
print "Train Accuracy for Logistic Regression Model",model_log.score(X_train,y_train)
print "Test Accuracy for Logistic Regression Model",model_log.score(X_test,y_test)
#Applying SVM on our data
from sklearn import svm
model_svm = svm.SVC()
model_svm = model_svm.fit(X_train,y_train)
print "Train Accuracy for SVM Model",model_svm.score(X_train,y_train)
print "Test Accuracy for SVM Model",model_svm.score(X_test,y_test)
from sklearn.tree import DecisionTreeClassifier
model_tree = DecisionTreeClassifier()
model_tree = model_tree.fit(X_train,y_train)
print "Train Accuracy for Decision Tree Model",model_tree.score(X_train,y_train)
print "Test Accuracy for Decison Tree Model",model_tree.score(X_test,y_test)
model_tree2 = DecisionTreeClassifier(max_depth=3)
model_tree2 = model_tree2.fit(X_train,y_train)
print "Train Accuracy for Decision Tree2 Model",model_tree2.score(X_train,y_train)
print "Test Accuracy for Decison Tree2 Model",model_tree2.score(X_test,y_test)

[[ 30.  64.   1.]
 [ 30.  62.   3.]
 [ 30.  65.   0.]
 [ 31.  59.   2.]
 [ 31.  65.   4.]
 [ 33.  58.  10.]
 [ 33.  60.   0.]
 [ 34.  59.   0.]
 [ 34.  66.   9.]
 [ 34.  58.  30.]
 [ 34.  60.   1.]
 [ 34.  61.  10.]
 [ 34.  67.   7.]
 [ 34.  60.   0.]
 [ 35.  64.  13.]
 [ 35.  63.   0.]
 [ 36.  60.   1.]
 [ 36.  69.   0.]
 [ 37.  60.   0.]
 [ 37.  63.   0.]
 [ 37.  58.   0.]
 [ 37.  59.   6.]
 [ 37.  60.  15.]
 [ 37.  63.   0.]
 [ 38.  69.  21.]
 [ 38.  59.   2.]
 [ 38.  60.   0.]
 [ 38.  60.   0.]
 [ 38.  62.   3.]
 [ 38.  64.   1.]
 [ 38.  66.   0.]
 [ 38.  66.  11.]
 [ 38.  60.   1.]
 [ 38.  67.   5.]
 [ 39.  66.   0.]
 [ 39.  63.   0.]
 [ 39.  67.   0.]
 [ 39.  58.   0.]
 [ 39.  59.   2.]
 [ 39.  63.   4.]
 [ 40.  58.   2.]
 [ 40.  58.   0.]
 [ 40.  65.   0.]
 [ 41.  60.  23.]
 [ 41.  64.   0.]
 [ 41.  67.   0.]
 [ 41.  58.   0.]
 [ 41.  59.   8.]
 [ 41.  59.   0.]
 [ 41.  64.   0.]
 [ 41.  69.   8.]
 [ 41.  65.   0.]
 [ 41.  65.   0.]
 [ 42.  69.   1.]
 [ 42.  59.   0.]
 [ 42.  58

C:\Users\Kabir\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Train Accuracy for Logistic Regression Model 0.745901639344
Test Accuracy for Logistic Regression Model 0.774193548387
Train Accuracy for SVM Model 0.901639344262
Test Accuracy for SVM Model 0.774193548387
Train Accuracy for Decision Tree Model 0.991803278689
Test Accuracy for Decison Tree Model 0.661290322581
Train Accuracy for Decision Tree2 Model 0.790983606557
Test Accuracy for Decison Tree2 Model 0.758064516129


In [2]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
print "precision of log Model", precision_score(y_test,model_log.predict(X_test))
print "recall of log Model", recall_score(y_test,model_log.predict(X_test))
print "f1score of log Model", f1_score(y_test,model_log.predict(X_test))
print "precision of svm Model", precision_score(y_test,model_svm.predict(X_test))
print "recall of svm Model", recall_score(y_test,model_svm.predict(X_test))
print "f1score of svm Model", f1_score(y_test,model_svm.predict(X_test))
print "precision of tree Model", precision_score(y_test,model_tree.predict(X_test))
print "recall of tree Model", recall_score(y_test,model_tree.predict(X_test))
print "f1score of tree Model", f1_score(y_test,model_tree.predict(X_test))
print "precision of tree2 Model", precision_score(y_test,model_tree2.predict(X_test))
print "recall of tree2 Model", recall_score(y_test,model_tree2.predict(X_test))
print "f1score of tree2 Model", f1_score(y_test,model_tree2.predict(X_test))
print "Best model for our data is LogisticRegression"


precision of log Model 0.803571428571
recall of log Model 0.9375
f1score of log Model 0.865384615385
precision of svm Model 0.774193548387
recall of svm Model 1.0
f1score of svm Model 0.872727272727
precision of tree Model 0.885714285714
recall of tree Model 0.645833333333
f1score of tree Model 0.746987951807
precision of tree2 Model 0.823529411765
recall of tree2 Model 0.875
f1score of tree2 Model 0.848484848485
Best model for our data is LogisticRegression
